server:
  port: 8082
  servlet:
    context-path: /springboot



spring:
  profiles:
    include:
      mysql,kafka,redis,dubbo,zk,es
  mail:
    username: 414162330@qq.com
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master: # 主数据源
        driverClassName: com.p6spy.engine.spy.P6SpyDriver
        username: root
        password: root
        url: jdbc:p6spy:mysql://localhost:3306/master?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      slave: # 从数据源
        driverClassName: com.p6spy.engine.spy.P6SpyDriver
        username: root
        password: root
        url: jdbc:p6spy:mysql://localhost:3306/slave?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8

mybatis:
  mapper-locations: classpath:mapper/*.xml
#分页
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
#zookeeper
zk:
  url: localhost:2181
  timeout: 1000
  retry: 3

p:
  name: ${com.properties.name}
  price: 3999
com:
  properties:
    name: '等闲变却故人心'
    title: '却道故人心易变'

management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 8083
    servlet:
      context-path: /sys
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator