server:
  port: 8081
  servlet:
    context-path: /springboot


spring:
  profiles:
    include:
      mysql,kafka,redis,dubbo,zk,es
  mail:
    username: 414162330@qq.com
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master: # 主数据源
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/master?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      slave: # 从数据源
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/slave?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
mybatis:
  mapper-locations: classpath:mapper/*.xml
#分页
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
#zookeeper
zk:
  url: 127.0.0.1:2181
  timeout: 1000
  retry: 3

p:
  name: '华为'
  price: 3999
com:
  properties:
    name: '人生若只如初见'
    title: '何事秋风悲画扇'
