server:
  port: 8088
  servlet:
    context-path: /springboot
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800 #最大工作线程数量
    min-spare-threads: 20 #最小工作线程数量
    max-connections: 10000 #一瞬间最大支持的并发的连接数
    accept-count: 200 #等待队列长度

#====================================spring Config===============================================

spring:
  profiles:
    include:
      mysql,kafka,redis,hystrix,seata,test
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    username: 414162330@qq.com

mybatis:
  config-location: classpath:/mybatis-config.xml
  dts:
    subscribe: springboot_user #接收方
    tables: springboot_user #发送方
    #env: dev

#打印sql
#logging:
#  level:
#    com.springboot.dao.generatedMapper.UserDTOMapper.selectByPrimaryKey: trace # 改成你的mapper文件所在包路径

###打印sql
sqlprinter:
  show: true
  format: true
  filter:
  # - com.github.dreamroute.sqlprinter.boot.mapper.UserMapper.selectById
  # - com.github.dreamroute.sqlprinter.boot.mapper.UserMapper.selectAll
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#分页
#pagehelper:
#  helperDialect: mysql
#  offsetAsPageNum: true
#  rowBoundsWithCount: true
#  reasonable: false
#====================================management Config===============================================
management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 8085
    servlet:
      context-path: /sys
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
#====================================gateway Config===============================================
api:
  gateway:
    http:
      app-name: order
      version: gray_1.0
      port: 8088
      admin-url: 127.0.0.1:9001
#====================================nacos Config===============================================
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
